# Generated by Django 4.0.2 on 2022-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
